package tk.sciwhiz12.concord.command;

import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.events.interaction.SlashCommandEvent;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.Mth;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.fml.loading.FMLLoader;
import tk.sciwhiz12.concord.Concord;
import tk.sciwhiz12.concord.command.discord.BanCommand;
import tk.sciwhiz12.concord.command.discord.CommandDispatcher;
import tk.sciwhiz12.concord.command.discord.KickCommand;
import tk.sciwhiz12.concord.command.discord.WhitelistCommand;

import java.awt.*;
import java.time.Instant;

/**
 * The Discord command hub.
 *
 * Has several sub-commands, some of which are usable by everyone:
 *  - list; lists players on the connected server.
 *  - tps; displays ticks per second in a format similar to /forge tps.
 *  - help; displays help autogenerated from the registered commands.
 * Some commands are only usable by administrators:
 *  - kick <user> [reason]; remove a user from the server, optionally with the specified reason. See @link{KickCommand}.
 *  - ban <user> [reason]; ban a user from the server, optionally with the specified reason. See @link{BanCommand}
 *  - whitelist <remove|add> <user>; add or remove a user from the server's whitelist. See @link{WhitelistCommand}
 *      The above commands are implemented separately, due to requirements of the option system.
 *  - stop; stop and shutdown the connected server. Disabled on singleplayer worlds.
 *
 * @author Curle
 */
public class ConcordDiscordCommand {
    private static JDA bot;
    private static MinecraftServer server;

    private static void listCommand(SlashCommandEvent listEvent) {
        listEvent.replyEmbeds(new EmbedBuilder()
                .setTitle("Concord Integrations")
                .setDescription("There are currently " + server.getPlayerCount() + " people online.")
                .addField("Online Players", String.join("\n", server.getPlayerNames()), false)
                .setTimestamp(Instant.now())
                .setColor(Color.CYAN)
                .build()
        ).setEphemeral(true).queue();
    }

    private static void tpsCommand(SlashCommandEvent tpsEvent) {
        double meanTickTime = Mth.average(server.tickTimes) * 1.0E-6D;;
        double meanTPS = Math.min(1000.0/meanTickTime, 20);

        StringBuilder builder = new StringBuilder();

        for (ServerLevel dim : server.getAllLevels()) {
            long[] times = server.getTickTime(dim.dimension());

            if (times == null)
                times = new long[]{0};

            double worldTickTime = Mth.average(times) * 1.0E-6D;;
            double worldTPS = Math.min(1000.0 / worldTickTime, 20);

            builder.append(dim.dimension().location()).append(": Mean tick time: ").append(worldTickTime).append(" ms. Mean TPS: ").append(worldTPS).append("\n");
        }

        tpsEvent.replyEmbeds(new EmbedBuilder()
                .setTitle("Concord integrations")
                .setDescription("TPS Performance Report")
                .addField("Overall performance", "Mean tick time: " + meanTickTime + " ms. Mean TPS: " + meanTPS, false)
                .addField("Performance per dimension", builder.toString(), false)
                .setColor(Color.ORANGE)
                .setTimestamp(Instant.now())
                .build()
        ).setEphemeral(true).queue();
    }

    private static void helpCommand(SlashCommandEvent helpEvent) {
        helpEvent.reply("TODO").queue();
        // TODO
    }

    private static void stopCommand(SlashCommandEvent stopEvent) {
        // Short-circuit if on integrated server
        if(FMLLoader.getDist() == Dist.CLIENT) {
            stopEvent.reply("Sorry! This command is disabled on Integrated servers.").setEphemeral(true).queue();
            return;
        }

        stopEvent.reply("Shutting the server down..").queue();
        Concord.BOT.getServer().halt(false);
    }

    public static void initialize(CommandDispatcher dispatcher) {
        dispatcher.registerSingle("list", "List all online users.", "Show a count of online users, and their names.", ConcordDiscordCommand::listCommand);
        dispatcher.registerSingle("tps", "Show the performance of the server.", "Display a breakdown of server performance, in current, average and separated by dimension.", ConcordDiscordCommand::tpsCommand);
        dispatcher.registerSingle("stop", "Shut down your Minecraft server.", "Immediately schedule the shutdown of the Minecraft server, akin to /stop from in-game.", ConcordDiscordCommand::stopCommand);
        dispatcher.registerSingle("help", "Show detailed information about every single available command.", "Show the help information you are currently reading.", ConcordDiscordCommand::helpCommand);

        dispatcher.registerSingle(KickCommand.INSTANCE);
        dispatcher.registerSingle(BanCommand.INSTANCE);
        dispatcher.registerSingle(WhitelistCommand.INSTANCE);
    }

    public static void postInit() {
        bot = Concord.BOT.getDiscord();
        server = Concord.BOT.getServer();
    }
}
