# suppress inspection "UnusedProperty" for whole file

# The information for the mod project
group=dev.sciwhiz12
modid=concord
author=sciwhiz12

neogradle.subsystems.decompiler.maxMemory=4g
org.gradle.caching=true

# Minecraft, Forge, and mappings versions
mc_version=1.21.11
neoforge_version=21.11.5-beta
mappings_channel=parchment
mappings_mc_version=1.21.10
mappings_version=2025.10.12
java_version=21

# Logging markers and console logging level
logging_markers=REGISTRIES
logging_console=debug

# Versions of dependencies
jda_version=5.3.0
