pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'ModdingInquisition'
            url = 'https://maven.moddinginquisition.org/releases'
        }
    }
}

rootProject.name = modid
