name: Publish Release

on:
  release:
    types: [ published ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: 'blob:none'

      - uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v6
        with:
          # Read-only cache if not on repo's default branch: https://stackoverflow.com/a/68414395
          cache-read-only: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}

      - run: ./gradlew build

      - name: Get version number
        id: version
        # Output of this step is the version number
        run: ./gradlew --console=plain -q :properties --property version | grep "^version:" | awk '{print "version=" $2}' >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v7
        with:
          name: Build artifacts
          path: build/libs/*.jar

      - name: Publish to GitHub Release
        uses: Kira-NT/mc-publish@v3.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.version.outputs.version }}

      - name: Publish to Modrinth
        if: ${{ vars.MODRINTH_ID != '' }}
        uses: Kira-NT/mc-publish@v3.3.0
        with:
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version: ${{ steps.version.outputs.version }}

      - name: Publish to CurseForge
        if: ${{ vars.CURSEFORGE_ID != '' }}
        uses: Kira-NT/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ vars.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version: ${{ steps.version.outputs.version }}
